# Generated by Django 3.2.5 on 2024-02-21 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_auto_20240221_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='created',
        ),
    ]
