# Generated by Django 3.2.5 on 2024-02-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_remove_products_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2024-02-21 00:00:00'),
            preserve_default=False,
        ),
    ]
