# Generated by Django 3.2.5 on 2024-02-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_hotdeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='related_products',
            field=models.ManyToManyField(blank=True, related_name='_shopapp_products_related_products_+', to='shopapp.Products'),
        ),
    ]
