# Generated by Django 3.2.5 on 2024-02-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0009_products_related_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='related_products',
        ),
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='shopapp.Category'),
        ),
    ]
