# Generated by Django 3.2.5 on 2024-02-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0010_auto_20240226_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotdeal',
            name='display',
            field=models.BooleanField(default=False, verbose_name='Special Discount'),
        ),
        migrations.AlterField(
            model_name='hotdeal',
            name='deal_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='shopapp.Category'),
        ),
    ]
